const SOURCES=[
  ['RTBF','site:rtbf.be'],['RTL info','site:rtl.be'],['La Libre','site:lalibre.be'],
  ['Le Soir','site:lesoir.be'],['BX1','site:bx1.be'],['La DH','site:dhnet.be'],
  ['Le Vif','site:levif.be'],["L'Avenir",'site:lavenir.net'],['Sudinfo','site:sudinfo.be']
];
const decode=(v='')=>v.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>');
const strip=(v='')=>decode(v).replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
const tag=(xml,name)=>{const m=xml.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,'i'));return m?decode(m[1]).trim():''};
async function get(url,timeout=7500){const c=new AbortController();const t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{signal:c.signal,redirect:'follow',headers:{'user-agent':'Mozilla/5.0 IHECS-Test-Actus/5.3'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r;}finally{clearTimeout(t)}}
const googleUrl=q=>`https://news.google.com/rss/search?q=${encodeURIComponent(`${q} when:45d`)}&hl=fr&gl=BE&ceid=BE:fr`;
function parse(xml,source){return (xml.match(/<item\b[\s\S]*?<\/item>/gi)||[]).map((item,i)=>{let title=strip(tag(item,'title')).replace(/\s+[–—-]\s+(RTBF|RTL info|La Libre|Le Soir|BX1|La DH|DHnet|Le Vif|L'Avenir|Sudinfo).*$/i,'').trim();const description=strip(tag(item,'description'));const dateRaw=tag(item,'pubDate');const d=dateRaw?new Date(dateRaw):new Date();return {id:`obit-${source}-${d.getTime()}-${i}`,title,description,source,url:strip(tag(item,'link')),date:d.toISOString()};}).filter(x=>x.title&&x.url)}
function candidate(title=''){const t=title.replace(/[«»“”"]/g,' ').replace(/\s+/g,' ').trim();const pats=[/(?:mort|décès|deces|disparition)\s+(?:de|du|d['’])\s*([A-ZÀ-ÖØ-Ý][A-Za-zÀ-ÿ'’.-]+(?:\s+[A-ZÀ-ÖØ-Ý][A-Za-zÀ-ÿ'’.-]+){1,3})/i,/^([A-ZÀ-ÖØ-Ý][A-Za-zÀ-ÿ'’.-]+(?:\s+[A-ZÀ-ÖØ-Ý][A-Za-zÀ-ÿ'’.-]+){1,3})\s+(?:est mort|est morte|est décédé|est décédée|s['’]est éteint|s['’]est éteinte)/i,/(?:adieu|hommage)\s+à\s+([A-ZÀ-ÖØ-Ý][A-Za-zÀ-ÿ'’.-]+(?:\s+[A-ZÀ-ÖØ-Ý][A-Za-zÀ-ÿ'’.-]+){1,3})/i];for(const p of pats){const m=t.match(p);if(m&&m[1])return m[1].trim();}return ''}
function strongDeath(title='',desc=''){const t=`${title} ${desc}`.toLowerCase();return /\b(est mort|est morte|est décédé|est décédée|décès de|deces de|mort de|disparition de|s['’]est éteint|s['’]est éteinte|nous a quittés|nous a quitté)\b/.test(t)}
async function wiki(person){if(!person||person.split(/\s+/).length<2)return null;try{const s=await get(`https://fr.wikipedia.org/w/api.php?action=query&list=search&srsearch=${encodeURIComponent(person)}&srlimit=2&format=json&origin=*`);const sj=await s.json();for(const hit of (sj?.query?.search||[])){const rr=await get(`https://fr.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(hit.title)}`);const j=await rr.json();const image=j?.thumbnail?.source||j?.originalimage?.source||'';if(image){let extract=(j?.extract||'').trim();if(extract.length>360)extract=extract.slice(0,357).replace(/\s+\S*$/,'')+'…';return {image,who:extract||`${j?.title||person} est une personnalité mentionnée dans l’actualité.`};}}}catch{}return null}
function cause(title='',desc=''){const t=`${title}. ${desc}`;const patterns=[/des suites (?:d['’]|de )([^.;]{3,100})/i,/à la suite d(?:e|['’]) ([^.;]{3,100})/i,/mort(?:e)? dans (un accident[^.;]{0,90})/i,/décéd(?:é|ée) dans (un accident[^.;]{0,90})/i,/emporté(?:e)? par ([^.;]{3,80})/i];for(const p of patterns){const m=t.match(p);if(m)return `La source indique : ${m[0].replace(/^[a-zà-ÿ]/,c=>c.toUpperCase())}.`;}return 'Cause du décès non précisée dans les informations publiques récupérées.'}
export default async function handler(req,res){res.setHeader('Cache-Control','s-maxage=1800, stale-while-revalidate=3600');try{const feeds=await Promise.allSettled(SOURCES.map(async([source,site])=>{const q=`${site} (\"est mort\" OR \"est décédé\" OR \"décès de\" OR \"mort de\" OR \"s'est éteint\")`;return parse(await (await get(googleUrl(q))).text(),source)}));const all=feeds.flatMap(x=>x.status==='fulfilled'?x.value:[]).filter(x=>strongDeath(x.title,x.description)).sort((a,b)=>new Date(b.date)-new Date(a.date));const dedup=[];const seen=new Set();for(const a of all){const p=candidate(a.title);if(!p)continue;const k=p.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');if(seen.has(k))continue;seen.add(k);dedup.push({...a,person:p});if(dedup.length>=24)break;}const rows=await Promise.all(dedup.map(async a=>{const w=await wiki(a.person);if(!w)return null;return {...a,image:w.image,who:w.who,cause:cause(a.title,a.description)}}));return res.status(200).json({generatedAt:new Date().toISOString(),items:rows.filter(Boolean).slice(0,16)});}catch(e){return res.status(500).json({error:'Impossible de charger la nécrologie',detail:String(e?.message||e)})}}
